config/routes.rb
Rails.application.routes.draw do
  resources :miis
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "miis#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mii.rb
class Mii < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/miis_controller.rb
class MiisController < ApplicationController
  before_action :set_mii, only: %i[ show edit update destroy ]

  # GET /miis or /miis.json
  def index
    @term = params[:term]
    if @term.present?
      @miis = Mii.where("name LIKE ?", "%#{@term}%")
    else
      @miis = Mii.all
    end
  end

  # GET /miis/1 or /miis/1.json
  def show
  end

  # GET /miis/new
  def new
    @mii = Mii.new
  end

  # GET /miis/1/edit
  def edit
  end

  # POST /miis or /miis.json
  def create
    @mii = Mii.new(mii_params)

    respond_to do |format|
      if @mii.save
        format.html { redirect_to mii_url(@mii), notice: "Mii was successfully created." }
        format.json { render :show, status: :created, location: @mii }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mii.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /miis/1 or /miis/1.json
  def update
    respond_to do |format|
      if @mii.update(mii_params)
        format.html { redirect_to mii_url(@mii), notice: "Mii was successfully updated." }
        format.json { render :show, status: :ok, location: @mii }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mii.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /miis/1 or /miis/1.json
  def destroy
    @mii.destroy!

    respond_to do |format|
      format.html { redirect_to miis_url, notice: "Mii was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mii
      @mii = Mii.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mii_params
      params.require(:mii).permit(:image, :name, :firstname, :nickname, :age, :keyword, :slogan, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/miis_helper.rb
module MiisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MMii</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Concert+One&family=Inter:wght@100..900&display=swap" rel="stylesheet">
  </head>

  <header>
  <nav class="navbar">
    <div class="container-fluid">
      <%= link_to "MMii", root_path, class: "navbar-brand"%>
      <form class="d-flex mx-auto" role="search" action="<%= miis_path %>" method="get">
        <input class="form-control" type="search" name="term" placeholder="Tapez un Nom">
        <button class="recherche" type="submit">Rechercher</button>
      </form>
      <%= link_to "Créer un Mmii", new_mii_path, class: "btn btn_create align-self-center"%>
    </div>
  </nav>
  </header>
  
  <body>

    <%= yield %>
  </body>
</html>

app/views/miis/_form.html.erb
<%= form_with(model: mii) do |form| %>
  <% if mii.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mii.errors.count, "error") %> prohibited this mii from being saved:</h2>

      <ul>
        <% mii.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_area :image %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :firstname, style: "display: block" %>
    <%= form.text_field :firstname %>
  </div>

  <div>
    <%= form.label :nickname, style: "display: block" %>
    <%= form.text_field :nickname %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :keyword, style: "display: block" %>
    <%= form.text_area :keyword %>
  </div>

  <div>
    <%= form.label :slogan, style: "display: block" %>
    <%= form.text_area :slogan %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/miis/_mii.html.erb
<div id="<%= dom_id mii %>">
  <p>
    <strong>Image:</strong>
    <%= image_tag mii.image %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= mii.name %>
  </p>

  <p>
    <strong>Firstname:</strong>
    <%= mii.firstname %>
  </p>

  <p>
    <strong>Nickname:</strong>
    <%= mii.nickname %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= mii.age %>
  </p>

  <p>
    <strong>Keyword:</strong>
    <%= mii.keyword %>
  </p>

  <p>
    <strong >Slogan:</strong>
    <%= mii.slogan %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= mii.description %>
  </p>
    
</div>

app/views/miis/edit.html.erb
<div class = "padding">
<h1>Editing mii</h1>

<%= render "form", mii: @mii %>

<br>

<div class = "padding_edit">
  <%= link_to "Voir ce Mmii", @mii, class: "btn" %> 
  <button <%= link_to "Retour à l'accueil", miis_path%> 
</div>

app/views/miis/index.html.erb
<p style="color: "><%= notice %></p>


<h1 class="titre_accueil text-center">MMii </h1>

<div id="miis" class="cards_gallery row row-cols-1 row-cols-md-4">
  <% @miis.each do |mii| %>
    <div class="col mb-4">
    <div class="card h-100">
      <img src="<%= mii.image %>" class="card-img-top" alt="Photo de <%= mii.firstname %> <%= mii.name %> ">
        <div class="card-body">
          <h5 class="card-title"><%= mii.firstname %> <%= mii.name %></h5>
          <%= link_to "Voir ce MMii", mii_path(mii), class: "btn btn_voir" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class ="cards_mii create">
<%= link_to "Créer un MMii", new_mii_path, class: "btn btn_create " %>
</div>

app/views/miis/new.html.erb
<div class = "padding">
<h1>Nouveau mii</h1>

<%= render "form", mii: @mii, class: "btn btn-primary" %>

<br>

<div class= "retour">
  <%= link_to "Retour à  l'accueil", miis_path, class: "btn btn_retour" %>
</div>

app/views/miis/show.html.erb
<p style="color: "><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col">
    <div style="width: 18rem;">
    <%= image_tag @mii.image, class: "card-img-top", alt: "Image de #{@mii}" %>
    <div class="card-body card_slogan shadow-sm p-3 mb-5 rounded">
      <p class="card-text">"<%= @mii.slogan %>"</p>
    </div>
<div>
<div class="modifier">
<%= link_to "Modifier ce MMii", edit_mii_path(@mii), class: "btn btn_modifier" %> 
</div>
  <%= button_to "Détruire ce MMii", @mii, method: :delete, class: "btn btn_delete" %>
  </div>
  </div>
    </div>
    <div class="col text-start">
    <h2><%= @mii.firstname%> <%= @mii.name%></h2>  
    <h6>#<%= @mii.keyword%></h6>
    <p>aka <%= @mii.nickname%></p>
    <p><%= @mii.age%> ans </p>
    <div class= "description shadow-sm p-3 mb-5 rounded">
    <p><strong>Description: </strong><br> <%= @mii.description%></p>
    </div class="retour">
    <%=link_to "Retour à l'accueil", miis_path, class: "btn btn_retour" %>
    </div>
    </div>
  </div>